name: Build FATE on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git ${{runner.workspace}}\vcpkg
        ${{runner.workspace}}\vcpkg\bootstrap-vcpkg.bat
        ${{runner.workspace}}\vcpkg\vcpkg integrate install
        echo "VCPKG_ROOT=${{runner.workspace}}\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Setup MSVC
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.18'

    - name: Configure CMake
      run: cmake -B ${{runner.workspace}}\build -S . -DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build ${{runner.workspace}}\build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FATE-executable
        path: ${{runner.workspace}}\build\outputs
